# The configuration file for the GenAI-MIDI-module

title = "Arturia Microfreak Configuration"
owner = "Charles Martin"
description = "Config for USB connection to an Arturia Microfreak"

# Basic config
log = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = true # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.h5"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
[midi]
in_device = "MicroFreak"
out_device = "MicroFreak"
input = [
  ["note_on", 1],
  ["control_change", 1, 2],
  ["control_change", 1, 5],
  ["control_change", 1, 9],
  ["control_change", 1, 10],
  ["control_change", 1, 12],
  ["control_change", 1, 13],
  ["control_change", 1, 23],
  ]
output = [
  ["note_on", 1],
  ["control_change", 1, 2],
  ["control_change", 1, 5],
  ["control_change", 1, 9],
  ["control_change", 1, 10],
  ["control_change", 1, 12],
  ["control_change", 1, 13],
  ["control_change", 1, 23],
]

# Websocket section enables websocket sending, remove to disable websocket sending
[websocket]
client_ip = "localhost" # "192.168.0.103" # The address to send messages to
client_port = 8765 # "3000" # The port to send messages to
server_ip = "localhost" # The address of this server
server_port = 5001 # The port this server should listen on.
