# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "Roland S-1 to S-1"
owner = "Charles Martin"
description = "A self-contained config for the Roland S-1"

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.tflite"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
# MIDI Mapping
[midi]
in_device = ["S-1", "X-TOUCH"]
out_device = ["S-1", "X-TOUCH"]
feedback_protection = true
input."X-TOUCH" = [ # XTOUCH-MINI knobs
  ["control_change", 11, 1], # XTOUCH-MINI knob controller 1
  ["control_change", 11, 2], # XTOUCH-MINI knob controller 2
  ["control_change", 11, 3], # XTOUCH-MINI knob controller 3
  ["control_change", 11, 4], # XTOUCH-MINI knob controller 4
  ["control_change", 11, 5], # XTOUCH-MINI knob controller 5 
  ["control_change", 11, 6], # XTOUCH-MINI knob controller 6
  ["control_change", 11, 7], # XTOUCH-MINI knob controller 7
  ["control_change", 11, 8], # XTOUCH-MINI knob controller 8
]
output."X-TOUCH" = [ # XTOUCH-MINI knobs
  ["control_change", 1, 9, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 10, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 11, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 12, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 13, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 14, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 15, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
  ["control_change", 1, 16, 0, 13], # XTOUCH-MINI ring (0-13 light up the LEDs)
]

input."S-1" = [
  ["note_on", 3], # notes input
  ["control_change", 3, 19], # osc square level
  ["control_change", 3, 20], # osc tri level
  ["control_change", 3, 21], # osc sub level
  # ["control_change", 3, 23], # osc noise level
  ["control_change", 3, 3], # lfo rate
  ["control_change", 3, 13], # osc lfo
  ["control_change", 3, 24], # filter env knob
  ["control_change", 3, 25], # filter lfo knob
  # ["control_change", 3, 71], # filter reso knob
]

output."S-1" = [
  ["note_on", 3], # notes input
  ["control_change", 3, 19], # osc square level
  ["control_change", 3, 20], # osc tri level
  ["control_change", 3, 21], # osc sub level
  # ["control_change", 3, 23], # osc noise level
  ["control_change", 3, 3], # lfo rate
  ["control_change", 3, 13], # osc lfo
  ["control_change", 3, 24], # filter env knob
  ["control_change", 3, 25], # filter lfo knob
  # ["control_change", 3, 71], # filter reso knob
]



  # ["control_change", 3, 3], # lfo rate
  # ["control_change", 3, 13], # osc lfo
  # ["control_change", 3, 3], # lfo rate
  # ["note_on", 3], # notes input

  # ["control_change", 3, 13], # osc lfo

